
# CACU05: ¿Qué intervalo de referencia se utiliza en cada observación?

PREFIX edintacus: <http://vocab.linkeddata.es/datosabiertos/def/contaminacionacustica#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?obs ?interval ?label
WHERE {
  ?obs a edintacus:NoiseObservation ;
       edintacus:noiseReferenceInterval ?interval .
  OPTIONAL { ?interval rdfs:label ?label }
}
