
# CACU07: ¿Cuántas observaciones hay por tipo de emisor predominante?

PREFIX edintacus: <https://edint.es/def/contaminacion-acustica#>

SELECT ?emitter (COUNT(?obs) AS ?count)
WHERE {
  ?obs a edintacus:NoiseObservation ;
       edintacus:noiseEmitterPredominantType ?emitter .
}
GROUP BY ?emitter
ORDER BY DESC(?count)